# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\ncozymemory\"\x07\n\x05\x45mpty\"\x0f\n\rHealthRequest\"\xb7\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x38\n\x07\x65ngines\x18\x02 \x03(\x0b\x32\'.cozymemory.HealthResponse.EnginesEntry\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x1aH\n\x0c\x45nginesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.cozymemory.EngineStatus:\x02\x38\x01\"O\n\x0c\x45ngineStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nlatency_ms\x18\x03 \x01(\x01\x12\r\n\x05\x65rror\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE_ENGINESENTRY']._loaded_options = None
  _globals['_HEALTHRESPONSE_ENGINESENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_HEALTHREQUEST']._serialized_start=37
  _globals['_HEALTHREQUEST']._serialized_end=52
  _globals['_HEALTHRESPONSE']._serialized_start=55
  _globals['_HEALTHRESPONSE']._serialized_end=238
  _globals['_HEALTHRESPONSE_ENGINESENTRY']._serialized_start=166
  _globals['_HEALTHRESPONSE_ENGINESENTRY']._serialized_end=238
  _globals['_ENGINESTATUS']._serialized_start=240
  _globals['_ENGINESTATUS']._serialized_end=319
# @@protoc_insertion_point(module_scope)
