# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cozymemory.grpc_server import conversation_pb2 as conversation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conversation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConversationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddConversation = channel.unary_unary(
                '/cozymemory.ConversationService/AddConversation',
                request_serializer=conversation__pb2.AddConversationRequest.SerializeToString,
                response_deserializer=conversation__pb2.AddConversationResponse.FromString,
                _registered_method=True)
        self.SearchConversations = channel.unary_unary(
                '/cozymemory.ConversationService/SearchConversations',
                request_serializer=conversation__pb2.SearchConversationsRequest.SerializeToString,
                response_deserializer=conversation__pb2.SearchConversationsResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/cozymemory.ConversationService/GetConversation',
                request_serializer=conversation__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=conversation__pb2.ConversationMemory.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/cozymemory.ConversationService/DeleteConversation',
                request_serializer=conversation__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=conversation__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.DeleteAllConversations = channel.unary_unary(
                '/cozymemory.ConversationService/DeleteAllConversations',
                request_serializer=conversation__pb2.DeleteAllConversationsRequest.SerializeToString,
                response_deserializer=conversation__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/cozymemory.ConversationService/ListConversations',
                request_serializer=conversation__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=conversation__pb2.SearchConversationsResponse.FromString,
                _registered_method=True)


class ConversationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddConversation,
                    request_deserializer=conversation__pb2.AddConversationRequest.FromString,
                    response_serializer=conversation__pb2.AddConversationResponse.SerializeToString,
            ),
            'SearchConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchConversations,
                    request_deserializer=conversation__pb2.SearchConversationsRequest.FromString,
                    response_serializer=conversation__pb2.SearchConversationsResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=conversation__pb2.GetConversationRequest.FromString,
                    response_serializer=conversation__pb2.ConversationMemory.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=conversation__pb2.DeleteConversationRequest.FromString,
                    response_serializer=conversation__pb2.DeleteResponse.SerializeToString,
            ),
            'DeleteAllConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllConversations,
                    request_deserializer=conversation__pb2.DeleteAllConversationsRequest.FromString,
                    response_serializer=conversation__pb2.DeleteResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=conversation__pb2.ListConversationsRequest.FromString,
                    response_serializer=conversation__pb2.SearchConversationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cozymemory.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cozymemory.ConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ConversationService/AddConversation',
            conversation__pb2.AddConversationRequest.SerializeToString,
            conversation__pb2.AddConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ConversationService/SearchConversations',
            conversation__pb2.SearchConversationsRequest.SerializeToString,
            conversation__pb2.SearchConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ConversationService/GetConversation',
            conversation__pb2.GetConversationRequest.SerializeToString,
            conversation__pb2.ConversationMemory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ConversationService/DeleteConversation',
            conversation__pb2.DeleteConversationRequest.SerializeToString,
            conversation__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAllConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ConversationService/DeleteAllConversations',
            conversation__pb2.DeleteAllConversationsRequest.SerializeToString,
            conversation__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ConversationService/ListConversations',
            conversation__pb2.ListConversationsRequest.SerializeToString,
            conversation__pb2.SearchConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
