# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cozymemory.grpc_server import conversation_pb2 as conversation__pb2
from cozymemory.grpc_server import knowledge_pb2 as knowledge__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDataset = channel.unary_unary(
                '/cozymemory.KnowledgeService/CreateDataset',
                request_serializer=knowledge__pb2.CreateDatasetRequest.SerializeToString,
                response_deserializer=knowledge__pb2.DatasetInfo.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/cozymemory.KnowledgeService/ListDatasets',
                request_serializer=knowledge__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=knowledge__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.AddKnowledge = channel.unary_unary(
                '/cozymemory.KnowledgeService/AddKnowledge',
                request_serializer=knowledge__pb2.AddKnowledgeRequest.SerializeToString,
                response_deserializer=knowledge__pb2.AddKnowledgeResponse.FromString,
                _registered_method=True)
        self.Cognify = channel.unary_unary(
                '/cozymemory.KnowledgeService/Cognify',
                request_serializer=knowledge__pb2.CognifyRequest.SerializeToString,
                response_deserializer=knowledge__pb2.CognifyResponse.FromString,
                _registered_method=True)
        self.SearchKnowledge = channel.unary_unary(
                '/cozymemory.KnowledgeService/SearchKnowledge',
                request_serializer=knowledge__pb2.SearchKnowledgeRequest.SerializeToString,
                response_deserializer=knowledge__pb2.SearchKnowledgeResponse.FromString,
                _registered_method=True)
        self.DeleteKnowledge = channel.unary_unary(
                '/cozymemory.KnowledgeService/DeleteKnowledge',
                request_serializer=knowledge__pb2.DeleteKnowledgeRequest.SerializeToString,
                response_deserializer=conversation__pb2.DeleteResponse.FromString,
                _registered_method=True)


class KnowledgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cognify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDataset,
                    request_deserializer=knowledge__pb2.CreateDatasetRequest.FromString,
                    response_serializer=knowledge__pb2.DatasetInfo.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=knowledge__pb2.ListDatasetsRequest.FromString,
                    response_serializer=knowledge__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'AddKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddKnowledge,
                    request_deserializer=knowledge__pb2.AddKnowledgeRequest.FromString,
                    response_serializer=knowledge__pb2.AddKnowledgeResponse.SerializeToString,
            ),
            'Cognify': grpc.unary_unary_rpc_method_handler(
                    servicer.Cognify,
                    request_deserializer=knowledge__pb2.CognifyRequest.FromString,
                    response_serializer=knowledge__pb2.CognifyResponse.SerializeToString,
            ),
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=knowledge__pb2.SearchKnowledgeRequest.FromString,
                    response_serializer=knowledge__pb2.SearchKnowledgeResponse.SerializeToString,
            ),
            'DeleteKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKnowledge,
                    request_deserializer=knowledge__pb2.DeleteKnowledgeRequest.FromString,
                    response_serializer=conversation__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cozymemory.KnowledgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cozymemory.KnowledgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.KnowledgeService/CreateDataset',
            knowledge__pb2.CreateDatasetRequest.SerializeToString,
            knowledge__pb2.DatasetInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.KnowledgeService/ListDatasets',
            knowledge__pb2.ListDatasetsRequest.SerializeToString,
            knowledge__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.KnowledgeService/AddKnowledge',
            knowledge__pb2.AddKnowledgeRequest.SerializeToString,
            knowledge__pb2.AddKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cognify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.KnowledgeService/Cognify',
            knowledge__pb2.CognifyRequest.SerializeToString,
            knowledge__pb2.CognifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.KnowledgeService/SearchKnowledge',
            knowledge__pb2.SearchKnowledgeRequest.SerializeToString,
            knowledge__pb2.SearchKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.KnowledgeService/DeleteKnowledge',
            knowledge__pb2.DeleteKnowledgeRequest.SerializeToString,
            conversation__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
