# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cozymemory.grpc_server import conversation_pb2 as conversation__pb2
from cozymemory.grpc_server import profile_pb2 as profile__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertProfile = channel.unary_unary(
                '/cozymemory.ProfileService/InsertProfile',
                request_serializer=profile__pb2.InsertProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.InsertProfileResponse.FromString,
                _registered_method=True)
        self.FlushProfile = channel.unary_unary(
                '/cozymemory.ProfileService/FlushProfile',
                request_serializer=profile__pb2.FlushProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.FlushProfileResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/cozymemory.ProfileService/GetProfile',
                request_serializer=profile__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.UserProfile.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/cozymemory.ProfileService/GetContext',
                request_serializer=profile__pb2.GetContextRequest.SerializeToString,
                response_deserializer=profile__pb2.GetContextResponse.FromString,
                _registered_method=True)
        self.AddProfileItem = channel.unary_unary(
                '/cozymemory.ProfileService/AddProfileItem',
                request_serializer=profile__pb2.AddProfileItemRequest.SerializeToString,
                response_deserializer=profile__pb2.AddProfileItemResponse.FromString,
                _registered_method=True)
        self.DeleteProfileItem = channel.unary_unary(
                '/cozymemory.ProfileService/DeleteProfileItem',
                request_serializer=profile__pb2.DeleteProfileItemRequest.SerializeToString,
                response_deserializer=conversation__pb2.DeleteResponse.FromString,
                _registered_method=True)


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProfileItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProfileItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertProfile,
                    request_deserializer=profile__pb2.InsertProfileRequest.FromString,
                    response_serializer=profile__pb2.InsertProfileResponse.SerializeToString,
            ),
            'FlushProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushProfile,
                    request_deserializer=profile__pb2.FlushProfileRequest.FromString,
                    response_serializer=profile__pb2.FlushProfileResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=profile__pb2.GetProfileRequest.FromString,
                    response_serializer=profile__pb2.UserProfile.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=profile__pb2.GetContextRequest.FromString,
                    response_serializer=profile__pb2.GetContextResponse.SerializeToString,
            ),
            'AddProfileItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProfileItem,
                    request_deserializer=profile__pb2.AddProfileItemRequest.FromString,
                    response_serializer=profile__pb2.AddProfileItemResponse.SerializeToString,
            ),
            'DeleteProfileItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProfileItem,
                    request_deserializer=profile__pb2.DeleteProfileItemRequest.FromString,
                    response_serializer=conversation__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cozymemory.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cozymemory.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ProfileService/InsertProfile',
            profile__pb2.InsertProfileRequest.SerializeToString,
            profile__pb2.InsertProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ProfileService/FlushProfile',
            profile__pb2.FlushProfileRequest.SerializeToString,
            profile__pb2.FlushProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ProfileService/GetProfile',
            profile__pb2.GetProfileRequest.SerializeToString,
            profile__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ProfileService/GetContext',
            profile__pb2.GetContextRequest.SerializeToString,
            profile__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProfileItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ProfileService/AddProfileItem',
            profile__pb2.AddProfileItemRequest.SerializeToString,
            profile__pb2.AddProfileItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProfileItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cozymemory.ProfileService/DeleteProfileItem',
            profile__pb2.DeleteProfileItemRequest.SerializeToString,
            conversation__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
