apiVersion: v1
kind: Service
metadata:
  name: cozymemory-api
  namespace: cozymemory
  labels:
    app: cozymemory-api
spec:
  type: ClusterIP
  selector:
    app: cozymemory-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
