/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服务健康检查
         * @description 检查服务及三大引擎（Mem0、Memobase、Cognee）的健康状态。
         *
         *     返回整体状态（`healthy` / `degraded` / `unhealthy`）及每个引擎的响应延迟。
         *     部分引擎不可用时整体状态为 `degraded`，不影响其他引擎正常使用。
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出用户所有记忆
         * @description 获取指定用户的全部记忆条目，按创建时间倒序。
         */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /**
         * 添加对话并提取记忆
         * @description 添加对话消息，Mem0 自动使用 LLM 提取事实性记忆并向量化存储。
         *
         *     `infer=true`（默认）：LLM 分析对话提取事实，如"用户喜欢篮球"。
         *     `infer=false`：原样存储消息内容，不做提取。
         */
        post: operations["add_conversation_api_v1_conversations_post"];
        /**
         * 删除用户所有记忆
         * @description 删除指定用户的全部记忆条目。
         */
        delete: operations["delete_all_conversations_api_v1_conversations_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 语义搜索记忆
         * @description 用自然语言语义搜索用户记忆。支持 `threshold` 过滤低相关结果。
         */
        post: operations["search_conversations_api_v1_conversations_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取单条记忆
         * @description 按 ID 获取单条记忆。记忆不存在返回 404。
         */
        get: operations["get_conversation_api_v1_conversations__memory_id__get"];
        put?: never;
        post?: never;
        /**
         * 删除单条记忆
         * @description 按 ID 删除单条记忆。
         */
        delete: operations["delete_conversation_api_v1_conversations__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 插入对话到缓冲区
         * @description 插入对话到 Memobase 缓冲区，自动提取画像
         */
        post: operations["insert_profile_api_v1_profiles_insert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 触发缓冲区处理
         * @description 触发缓冲区处理
         */
        post: operations["flush_profile_api_v1_profiles_flush_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户画像
         * @description 获取用户结构化画像
         */
        get: operations["get_profile_api_v1_profiles__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{user_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 获取 LLM 上下文提示词
         * @description 获取上下文提示词
         */
        post: operations["get_context_api_v1_profiles__user_id__context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{user_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手动添加画像条目
         * @description 手动添加画像条目
         */
        post: operations["add_profile_item_api_v1_profiles__user_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{user_id}/items/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除画像条目
         * @description 删除画像条目
         */
        delete: operations["delete_profile_item_api_v1_profiles__user_id__items__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出所有数据集
         * @description 列出所有数据集
         */
        get: operations["list_datasets_api_v1_knowledge_datasets_get"];
        put?: never;
        /**
         * 创建数据集
         * @description 创建数据集
         */
        post: operations["create_dataset_api_v1_knowledge_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除数据集
         * @description 删除指定数据集及其中所有文档与图谱数据。此操作不可逆。
         *
         *     `dataset_id` 为 `GET /knowledge/datasets` 返回的 UUID。
         */
        delete: operations["delete_dataset_api_v1_knowledge_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加文档到知识库
         * @description 添加文档到知识库
         */
        post: operations["add_knowledge_api_v1_knowledge_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/cognify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 构建知识图谱
         * @description 触发知识图谱构建
         */
        post: operations["cognify_api_v1_knowledge_cognify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 搜索知识库
         * @description 搜索知识库
         */
        post: operations["search_knowledge_api_v1_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/cognify/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询 Cognify 任务状态
         * @description 查询知识图谱构建任务的当前状态。
         *
         *     `job_id` 为 `POST /knowledge/cognify` 返回的 `pipeline_run_id`。
         */
        get: operations["get_cognify_status_api_v1_knowledge_cognify_status__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/datasets/{dataset_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取数据集知识图谱
         * @description 获取指定数据集的知识图谱结构（节点 + 边），供前端可视化使用。
         */
        get: operations["get_dataset_graph_api_v1_knowledge_datasets__dataset_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除知识数据
         * @description 删除知识数据
         */
        delete: operations["delete_knowledge_api_v1_knowledge_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 并发获取三类记忆（统一上下文）
         * @description 一次请求并发调用 Mem0、Memobase、Cognee，返回合并后的统一上下文。
         *
         *     **适用场景**：LLM 调用前的上下文准备阶段，用单次往返替代三次串行请求。
         *
         *     **延迟特性**：总延迟 = max(各引擎延迟)，而非各引擎延迟之和。
         *
         *     **容错特性**：某个引擎失败时，其他引擎结果正常返回，
         *     失败原因记录在响应的 `errors` 字段中。
         *
         *     **query 行为**：
         *     - 有值 → Mem0 语义搜索 + Cognee 知识图谱检索
         *     - 为 null → Mem0 返回全量记忆（按时间倒序），Cognee 自动跳过
         */
        post: operations["get_unified_context_api_v1_context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出所有已知用户
         * @description 列出 Redis 中所有已建立 UUID 映射的 user_id，按字母排序。
         *
         *     扫描 `cm:uid:*` 键空间，适用于用户管理和调试场景。
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/uuid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询用户 UUID 映射
         * @description 查询 user_id 对应的 UUID v4 映射。
         *
         *     - `create=false`（默认）：只读，映射不存在返回 404。
         *     - `create=true`：若映射不存在则原子创建并返回，同时 `created=true` 标识本次新建。
         *
         *     Memobase 要求 user_id 必须是 UUID v4，本接口供调试或预热映射使用。
         *     正常调用画像接口时映射会自动创建，无需手动调用。
         */
        get: operations["get_uuid_api_v1_users__user_id__uuid_get"];
        put?: never;
        post?: never;
        /**
         * 删除用户 UUID 映射
         * @description 删除 user_id 的 Redis 映射记录。
         *
         *     **警告**：此操作不会删除 Memobase 中的实际画像数据。
         *     删除映射后，下次调用画像接口将自动生成新的 UUID，旧 UUID 对应的
         *     Memobase 用户数据将永久无法通过 CozyMemory 接口访问（数据孤立）。
         *
         *     若需彻底清除画像数据，请在删除映射前先调用
         *     `DELETE /api/v1/profiles/{user_id}/items/{profile_id}` 逐条删除，
         *     或通过 Memobase 直接操作。
         */
        delete: operations["delete_uuid_mapping_api_v1_users__user_id__uuid_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/export/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出用户记忆为 JSON bundle */
        get: operations["export_user_api_v1_backup_export__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从 bundle 恢复用户记忆 */
        post: operations["import_bundle_api_v1_backup_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_api_v1_admin_api_keys_get"];
        put?: never;
        /** Create Key */
        post: operations["create_key_api_v1_admin_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Key */
        delete: operations["delete_key_api_v1_admin_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        /** Update Key */
        patch: operations["update_key_api_v1_admin_api_keys__key_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/api-keys/{key_id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Key */
        post: operations["rotate_key_api_v1_admin_api_keys__key_id__rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/api-keys/{key_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看该 key 最近使用记录 */
        get: operations["get_key_logs_api_v1_admin_api_keys__key_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreateRequest */
        ApiKeyCreateRequest: {
            /**
             * Name
             * @description 人可读命名
             */
            name: string;
        };
        /**
         * ApiKeyCreateResponse
         * @description 创建/轮换响应 — 仅此刻返回明文 key，用户必须立即保存
         */
        ApiKeyCreateResponse: {
            record: components["schemas"]["ApiKeyRecord"];
            /**
             * Key
             * @description 明文 key（仅此次返回，之后只存 hash）
             */
            key: string;
        };
        /** ApiKeyListResponse */
        ApiKeyListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["ApiKeyRecord"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * ApiKeyLogEntry
         * @description 单次 API key 使用记录
         */
        ApiKeyLogEntry: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Status */
            status: number;
        };
        /** ApiKeyLogListResponse */
        ApiKeyLogListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: components["schemas"]["ApiKeyLogEntry"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * ApiKeyRecord
         * @description 服务端存储的 API key 元数据（不含明文和 hash）
         */
        ApiKeyRecord: {
            /**
             * Id
             * @description key ID（UUID）
             */
            id: string;
            /**
             * Name
             * @description 人可读命名
             */
            name: string;
            /**
             * Prefix
             * @description key 前缀，供识别，例如 cozy_prod_a1b2c3
             */
            prefix: string;
            /**
             * Created At
             * Format: date-time
             * @description 创建时间
             */
            created_at: string;
            /**
             * Last Used At
             * @description 最近一次成功鉴权时间
             */
            last_used_at?: string | null;
            /**
             * Disabled
             * @description 禁用后不再通过鉴权
             * @default false
             */
            disabled: boolean;
        };
        /** ApiKeyUpdateRequest */
        ApiKeyUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Disabled */
            disabled?: boolean | null;
        };
        /**
         * BackupImportRequest
         * @description 导入请求体
         */
        BackupImportRequest: {
            /** @description 完整导出包 */
            bundle: components["schemas"]["MemoryBundle"];
            /**
             * Target User Id
             * @description 可选重映射目标；为空则用 bundle.user_id。允许把一个账号的记忆导入到另一个账号
             */
            target_user_id?: string | null;
        };
        /**
         * BackupImportResponse
         * @description 导入结果
         */
        BackupImportResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** User Id */
            user_id: string;
            /**
             * Conversations Imported
             * @default 0
             */
            conversations_imported: number;
            /**
             * Conversations Skipped
             * @default 0
             */
            conversations_skipped: number;
            /**
             * Profiles Imported
             * @default 0
             */
            profiles_imported: number;
            /**
             * Profiles Skipped
             * @default 0
             */
            profiles_skipped: number;
            /**
             * Errors
             * @description 每条失败记录的 kind + id + reason
             */
            errors?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CognifyStatusResponse
         * @description Cognify 任务状态响应（透传 Cognee 原始响应）
         */
        CognifyStatusResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @description 状态: pending/running/completed/failed/unknown
             * @default unknown
             */
            status: string;
            /**
             * Data
             * @description Cognee 原始响应数据
             */
            data?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ContextRequest
         * @description 统一上下文请求
         * @example {
         *       "agent_id": "sales-agent",
         *       "chats": [
         *         {
         *           "content": "你好，我最近喜欢游泳",
         *           "role": "user"
         *         }
         *       ],
         *       "conversation_limit": 5,
         *       "engine_timeout": 5,
         *       "include_conversations": true,
         *       "include_knowledge": true,
         *       "include_profile": true,
         *       "knowledge_datasets": [
         *         "product-catalog",
         *         "pricing"
         *       ],
         *       "knowledge_search_type": "GRAPH_COMPLETION",
         *       "knowledge_top_k": 3,
         *       "max_token_size": 500,
         *       "memory_scope": "both",
         *       "query": "用户最近关心什么话题",
         *       "session_id": "sess_20260419_001",
         *       "user_id": "user_01"
         *     }
         */
        ContextRequest: {
            /**
             * User Id
             * @description 用户 ID。include_profile=true 时必须为 UUID v4（Memobase 限制）
             */
            user_id: string;
            /**
             * Agent Id
             * @description 智能体 ID（如 sales-agent）。用于按 agent 隔离 Mem0 记忆视角
             */
            agent_id?: string | null;
            /**
             * Session Id
             * @description 会话 ID。memory_scope=short/both 时用于短期记忆过滤
             */
            session_id?: string | null;
            /**
             * Query
             * @description 语义查询文本。有值时驱动 Mem0 语义搜索和 Cognee 知识检索；为 null 时 Mem0 返回全量记忆，Cognee 跳过
             */
            query?: string | null;
            /**
             * Memory Scope
             * @description 记忆范围：short=仅本 session 短期记忆 / long=全量历史长期记忆（默认）/ both=同时返回短期和长期（响应中拆分为 short_term_memories + long_term_memories）
             * @default long
             * @enum {string}
             */
            memory_scope: "short" | "long" | "both";
            /**
             * Include Conversations
             * @description 是否包含 Mem0 对话记忆
             * @default true
             */
            include_conversations: boolean;
            /**
             * Include Profile
             * @description 是否包含 Memobase 用户画像上下文
             * @default true
             */
            include_profile: boolean;
            /**
             * Include Knowledge
             * @description 是否包含 Cognee 知识图谱结果（需提供 query）
             * @default true
             */
            include_knowledge: boolean;
            /**
             * Conversation Limit
             * @description Mem0 返回条数限制
             * @default 5
             */
            conversation_limit: number;
            /**
             * Max Token Size
             * @description Memobase 上下文最大 token 数
             * @default 500
             */
            max_token_size: number;
            /**
             * Knowledge Datasets
             * @description Cognee 查询的数据集列表。null 或空列表表示搜索全部数据集
             */
            knowledge_datasets?: string[] | null;
            /**
             * Knowledge Top K
             * @description Cognee 返回结果数量
             * @default 3
             */
            knowledge_top_k: number;
            /**
             * Knowledge Search Type
             * @description Cognee 搜索类型
             * @default GRAPH_COMPLETION
             * @enum {string}
             */
            knowledge_search_type: "CHUNKS" | "SUMMARIES" | "RAG_COMPLETION" | "GRAPH_COMPLETION";
            /**
             * Engine Timeout
             * @description 每个引擎的超时时间（秒）。超时的引擎结果以错误形式记录在 errors 字段，不影响其他引擎的结果。为 null 时不限制单引擎超时
             */
            engine_timeout?: number | null;
            /**
             * Chats
             * @description 当前对话轮次，传给 Memobase 以生成与当前对话更相关的上下文提示词。注意：Memobase context 端点当前为 GET-only，此参数透传至服务层但暂不生效
             */
            chats?: components["schemas"]["Message"][] | null;
        };
        /**
         * ContextResponse
         * @description 统一上下文响应
         */
        ContextResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * User Id
             * @description 用户 ID
             */
            user_id: string;
            /**
             * Conversations
             * @description Mem0 对话记忆列表（向后兼容字段）。memory_scope=both 时等同于 long_term_memories
             */
            conversations?: components["schemas"]["ConversationMemory"][];
            /**
             * Short Term Memories
             * @description 当前 session 的短期记忆（memory_scope=short/both 时填充）
             */
            short_term_memories?: components["schemas"]["ConversationMemory"][];
            /**
             * Long Term Memories
             * @description 跨 session 的长期记忆（memory_scope=long/both 时填充）
             */
            long_term_memories?: components["schemas"]["ConversationMemory"][];
            /**
             * Profile Context
             * @description Memobase 生成的 LLM 上下文提示词，可直接插入 system prompt
             */
            profile_context?: string | null;
            /**
             * Knowledge
             * @description Cognee 知识图谱搜索结果
             */
            knowledge?: components["schemas"]["KnowledgeSearchResult"][];
            /**
             * Errors
             * @description 各引擎的错误信息，键为引擎域名 (conversations/profile/knowledge)。有错误时对应字段返回空值，其他引擎结果不受影响
             */
            errors?: {
                [key: string]: string;
            };
            /**
             * Latency Ms
             * @description 本次请求总耗时（毫秒），等于各引擎最长耗时
             */
            latency_ms: number;
        };
        /**
         * ConversationMemory
         * @description Mem0 返回的单条记忆（提取出的事实）
         */
        ConversationMemory: {
            /**
             * Id
             * @description 记忆 ID
             */
            id: string;
            /**
             * User Id
             * @description 用户 ID
             */
            user_id: string;
            /**
             * Content
             * @description 提取的事实内容
             */
            content: string;
            /**
             * Score
             * @description 搜索相似度分数
             */
            score?: number | null;
            /**
             * Metadata
             * @description 元数据
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * @description 创建时间
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description 更新时间
             */
            updated_at?: string | null;
        };
        /**
         * ConversationMemoryCreate
         * @description 添加对话请求 → Mem0 自动提取事实
         * @example {
         *       "agent_id": "sales-agent",
         *       "infer": true,
         *       "messages": [
         *         {
         *           "content": "我最近开始学打篮球，感觉很有趣",
         *           "role": "user"
         *         },
         *         {
         *           "content": "太棒了！篮球是很好的运动",
         *           "role": "assistant"
         *         }
         *       ],
         *       "metadata": {
         *         "source": "web"
         *       },
         *       "session_id": "sess_abc123",
         *       "user_id": "user_01"
         *     }
         */
        ConversationMemoryCreate: {
            /**
             * User Id
             * @description 用户 ID
             */
            user_id: string;
            /**
             * Agent Id
             * @description 智能体 ID，按 agent 隔离记忆视角
             */
            agent_id?: string | null;
            /**
             * Session Id
             * @description 会话 ID，映射到 Mem0 run_id（短期记忆）
             */
            session_id?: string | null;
            /**
             * Messages
             * @description 对话消息列表
             */
            messages: components["schemas"]["Message"][];
            /**
             * Metadata
             * @description 元数据 (source 等)
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Infer
             * @description 是否使用 LLM 提取事实。False 则原样存储
             * @default true
             */
            infer: boolean;
        };
        /**
         * ConversationMemoryListResponse
         * @description 记忆列表响应
         *
         *     memory_scope=both 时，short_term_memories / long_term_memories 分别填充；
         *     data 保持向后兼容，等同于 long_term_memories（或 short_term_memories 当 scope=short）。
         */
        ConversationMemoryListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data?: components["schemas"]["ConversationMemory"][];
            /**
             * Total
             * @description 总数
             * @default 0
             */
            total: number;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Short Term Memories
             * @description 会话级短期记忆（memory_scope=short/both 时填充）
             */
            short_term_memories?: components["schemas"]["ConversationMemory"][];
            /**
             * Long Term Memories
             * @description 跨会话长期记忆（memory_scope=long/both 时填充）
             */
            long_term_memories?: components["schemas"]["ConversationMemory"][];
        };
        /**
         * ConversationMemorySearch
         * @description 搜索会话记忆
         * @example {
         *       "agent_id": "sales-agent",
         *       "limit": 5,
         *       "memory_scope": "long",
         *       "query": "用户喜欢什么运动",
         *       "session_id": "sess_abc123",
         *       "threshold": 0.7,
         *       "user_id": "user_01"
         *     }
         */
        ConversationMemorySearch: {
            /**
             * User Id
             * @description 用户 ID
             */
            user_id: string;
            /**
             * Agent Id
             * @description 限定智能体视角，None 则搜索该用户的全部记忆
             */
            agent_id?: string | null;
            /**
             * Session Id
             * @description 限定会话（memory_scope=short/both 时生效）
             */
            session_id?: string | null;
            /**
             * Query
             * @description 搜索查询文本
             */
            query: string;
            /**
             * Limit
             * @description 返回数量限制
             * @default 10
             */
            limit: number;
            /**
             * Threshold
             * @description 最低相似度阈值
             */
            threshold?: number | null;
            /**
             * Memory Scope
             * @description 记忆范围：short=仅本 session / long=全量历史（默认）/ both=两者均返回
             * @default long
             * @enum {string}
             */
            memory_scope: "short" | "long" | "both";
        };
        /**
         * DatasetGraphResponse
         * @description 数据集知识图谱响应（透传 Cognee 原始图谱数据）
         */
        DatasetGraphResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Dataset Id */
            dataset_id: string;
            /**
             * Data
             * @description Cognee 图谱原始数据（nodes + edges）
             */
            data?: unknown;
        } & {
            [key: string]: unknown;
        };
        /**
         * EngineStatus
         * @description 引擎健康状态
         */
        EngineStatus: {
            /**
             * Name
             * @description 引擎名称
             */
            name: string;
            /**
             * Status
             * @description 状态: healthy / unhealthy
             */
            status: string;
            /**
             * Latency Ms
             * @description 响应延迟(ms)
             */
            latency_ms?: number | null;
            /**
             * Error
             * @description 错误信息
             */
            error?: string | null;
        };
        /**
         * ErrorResponse
         * @description 错误响应
         * @example {
         *       "detail": "upstream timeout after 3 retries",
         *       "engine": "Mem0",
         *       "error": "Mem0Error",
         *       "success": false
         *     }
         */
        ErrorResponse: {
            /**
             * Success
             * @default false
             */
            success: boolean;
            /**
             * Error
             * @description 错误类型
             */
            error: string;
            /**
             * Detail
             * @description 错误详情
             */
            detail?: string | null;
            /**
             * Engine
             * @description 出错的引擎名称
             */
            engine?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应
         */
        HealthResponse: {
            /**
             * Status
             * @description 整体状态: healthy / degraded / unhealthy
             */
            status: string;
            /** Engines */
            engines?: {
                [key: string]: components["schemas"]["EngineStatus"];
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /**
         * KnowledgeAddRequest
         * @description 添加文档到知识库
         * @example {
         *       "data": "CozyMemory 是统一 AI 记忆平台，整合了 Mem0、Memobase 和 Cognee 三大引擎",
         *       "dataset": "default"
         *     }
         */
        KnowledgeAddRequest: {
            /**
             * Data
             * @description 文本内容或文件路径
             */
            data: string;
            /**
             * Dataset
             * @description 数据集名称
             */
            dataset: string;
            /**
             * Node Set
             * @description 节点集标识
             */
            node_set?: string[] | null;
        };
        /**
         * KnowledgeAddResponse
         * @description 添加文档响应
         */
        KnowledgeAddResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Data Id
             * @description 数据项 ID
             */
            data_id?: string | null;
            /** Dataset Name */
            dataset_name?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * KnowledgeCognifyRequest
         * @description 触发知识图谱构建
         * @example {
         *       "datasets": [
         *         "default"
         *       ],
         *       "run_in_background": true
         *     }
         */
        KnowledgeCognifyRequest: {
            /**
             * Datasets
             * @description 要处理的数据集列表，为 null 则处理全部
             */
            datasets?: string[] | null;
            /**
             * Run In Background
             * @description 是否后台运行（推荐 true，图谱构建耗时较长）
             * @default true
             */
            run_in_background: boolean;
        };
        /**
         * KnowledgeCognifyResponse
         * @description 知识图谱构建响应
         */
        KnowledgeCognifyResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Pipeline Run Id
             * @description 管道运行 ID
             */
            pipeline_run_id?: string | null;
            /**
             * Status
             * @description 状态: pending/running/completed/failed
             * @default pending
             */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * KnowledgeDataset
         * @description 数据集信息
         */
        KnowledgeDataset: {
            /**
             * Id
             * @description 数据集 ID (UUID)
             */
            id: string;
            /**
             * Name
             * @description 数据集名称
             */
            name: string;
            /**
             * Created At
             * @description 创建时间
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description 更新时间
             */
            updated_at?: string | null;
        };
        /**
         * KnowledgeDatasetListResponse
         * @description 数据集列表响应
         */
        KnowledgeDatasetListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data?: components["schemas"]["KnowledgeDataset"][];
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * KnowledgeDeleteRequest
         * @description 删除知识数据请求
         */
        KnowledgeDeleteRequest: {
            /**
             * Data Id
             * @description 数据项 ID
             */
            data_id: string;
            /**
             * Dataset Id
             * @description 数据集 ID
             */
            dataset_id: string;
        };
        /**
         * KnowledgeDeleteResponse
         * @description 删除知识数据响应
         */
        KnowledgeDeleteResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * KnowledgeSearchRequest
         * @description 知识库搜索
         * @example {
         *       "dataset": "default",
         *       "query": "AI 记忆服务有哪些核心能力",
         *       "search_type": "CHUNKS",
         *       "top_k": 5
         *     }
         */
        KnowledgeSearchRequest: {
            /**
             * Query
             * @description 搜索查询
             */
            query: string;
            /**
             * Dataset
             * @description 限定数据集，为 null 则搜索全部
             */
            dataset?: string | null;
            /**
             * Search Type
             * @description 搜索类型：CHUNKS（原文片段）/ SUMMARIES（摘要）/ RAG_COMPLETION（RAG 生成）/ GRAPH_COMPLETION（图谱推理，最强）
             * @default GRAPH_COMPLETION
             * @enum {string}
             */
            search_type: "CHUNKS" | "SUMMARIES" | "RAG_COMPLETION" | "GRAPH_COMPLETION";
            /**
             * Top K
             * @description 返回数量限制
             * @default 10
             */
            top_k: number;
        };
        /**
         * KnowledgeSearchResponse
         * @description 搜索响应
         */
        KnowledgeSearchResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data?: components["schemas"]["KnowledgeSearchResult"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * KnowledgeSearchResult
         * @description 搜索结果
         */
        KnowledgeSearchResult: {
            /**
             * Id
             * @description 结果 ID
             */
            id?: string | null;
            /**
             * Text
             * @description 结果文本内容
             */
            text?: string | null;
            /**
             * Score
             * @description 相关性分数
             */
            score?: number | null;
            /**
             * Metadata
             * @description 附加元数据
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MemoryBundle
         * @description 单用户记忆导出包。version 用于未来 schema 演化时做兼容判断。
         */
        MemoryBundle: {
            /**
             * Version
             * @description Schema 版本
             * @default 1.0
             */
            version: string;
            /**
             * Exported At
             * Format: date-time
             * @description 导出时间
             */
            exported_at: string;
            /**
             * User Id
             * @description 记忆所属用户 ID
             */
            user_id: string;
            /**
             * Conversations
             * @description Mem0 对话记忆快照
             */
            conversations?: components["schemas"]["ConversationMemory"][];
            /**
             * Profile Topics
             * @description Memobase 用户画像主题
             */
            profile_topics?: components["schemas"]["ProfileTopic"][];
        };
        /**
         * Message
         * @description 对话消息（Mem0 和 Memobase 共用）
         */
        Message: {
            /**
             * Role
             * @description 角色: user / assistant / system
             */
            role: string;
            /**
             * Content
             * @description 消息内容
             */
            content: string;
            /**
             * Created At
             * @description 消息时间戳 (ISO 8601)
             */
            created_at?: string | null;
        };
        /**
         * ProfileAddItemRequest
         * @description 手动添加画像条目请求
         * @example {
         *       "content": "喜欢游泳和跑步，每周运动 3 次",
         *       "sub_topic": "sport",
         *       "topic": "interest"
         *     }
         */
        ProfileAddItemRequest: {
            /**
             * Topic
             * @description 主题 (如 basic_info, interest)
             */
            topic: string;
            /**
             * Sub Topic
             * @description 子主题 (如 name, hobby)
             */
            sub_topic: string;
            /**
             * Content
             * @description 内容
             */
            content: string;
        };
        /**
         * ProfileAddItemResponse
         * @description 手动添加画像条目响应
         */
        ProfileAddItemResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** @description 添加的画像条目 */
            data?: components["schemas"]["ProfileTopic"] | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ProfileContext
         * @description 上下文提示词结果
         */
        ProfileContext: {
            /**
             * User Id
             * @description 用户 ID
             */
            user_id: string;
            /**
             * Context
             * @description 可直接插入 LLM prompt 的文本
             */
            context: string;
        };
        /**
         * ProfileContextRequest
         * @description 获取上下文提示词请求（user_id 来自路径参数）
         * @example {
         *       "max_token_size": 500
         *     }
         */
        ProfileContextRequest: {
            /**
             * Max Token Size
             * @description 上下文最大 token 数
             * @default 500
             */
            max_token_size: number;
            /**
             * Chats
             * @description 近期对话（用于语义搜索匹配）
             */
            chats?: components["schemas"]["Message"][] | null;
        };
        /**
         * ProfileContextResponse
         * @description 获取上下文响应
         */
        ProfileContextResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** @description 上下文提示词 */
            data?: components["schemas"]["ProfileContext"] | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ProfileDeleteItemResponse
         * @description 删除画像条目响应
         */
        ProfileDeleteItemResponse: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ProfileFlushRequest
         * @description 触发缓冲区处理
         */
        ProfileFlushRequest: {
            /**
             * User Id
             * @description 用户 ID
             */
            user_id: string;
            /**
             * Sync
             * @description 是否同步等待处理完成
             * @default false
             */
            sync: boolean;
        };
        /**
         * ProfileFlushResponse
         * @description 缓冲区处理响应
         */
        ProfileFlushResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ProfileGetResponse
         * @description 获取画像响应
         */
        ProfileGetResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** @description 用户画像数据 */
            data?: components["schemas"]["UserProfile"] | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ProfileInsertRequest
         * @description 插入对话到 Memobase 缓冲区
         * @example {
         *       "messages": [
         *         {
         *           "content": "我叫小明，今年 28 岁，住在北京",
         *           "role": "user"
         *         },
         *         {
         *           "content": "好的，我已记录您的基本信息",
         *           "role": "assistant"
         *         }
         *       ],
         *       "sync": false,
         *       "user_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         */
        ProfileInsertRequest: {
            /**
             * User Id
             * @description 用户 ID（必须是 UUID v4 格式）
             */
            user_id: string;
            /**
             * Messages
             * @description 对话消息列表
             */
            messages: components["schemas"]["Message"][];
            /**
             * Sync
             * @description 是否同步等待处理完成
             * @default false
             */
            sync: boolean;
        };
        /**
         * ProfileInsertResponse
         * @description 插入响应
         */
        ProfileInsertResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** User Id */
            user_id: string;
            /**
             * Blob Id
             * @description Blob ID
             */
            blob_id?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ProfileTopic
         * @description 画像中的单个主题条目
         */
        ProfileTopic: {
            /**
             * Id
             * @description 条目 ID
             */
            id: string;
            /**
             * Topic
             * @description 主题 (如 basic_info, interest)
             */
            topic: string;
            /**
             * Sub Topic
             * @description 子主题 (如 name, hobby)
             */
            sub_topic: string;
            /**
             * Content
             * @description 内容
             */
            content: string;
            /**
             * Created At
             * @description 创建时间
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description 更新时间
             */
            updated_at?: string | null;
        };
        /** UserListResponse */
        UserListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data: string[];
            /** Total */
            total: number;
        };
        /** UserMappingDeleteResponse */
        UserMappingDeleteResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /**
             * Warning
             * @default
             */
            warning: string;
        };
        /** UserMappingResponse */
        UserMappingResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** User Id */
            user_id: string;
            /** Uuid */
            uuid: string;
            /**
             * Created
             * @default false
             */
            created: boolean;
        };
        /**
         * UserProfile
         * @description 完整用户画像
         */
        UserProfile: {
            /**
             * User Id
             * @description 用户 ID
             */
            user_id: string;
            /**
             * Topics
             * @description 画像主题列表
             */
            topics?: components["schemas"]["ProfileTopic"][];
            /** Updated At */
            updated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query: {
                user_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMemoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationMemoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMemoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_all_conversations_api_v1_conversations_delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMemoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_conversations_api_v1_conversations_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationMemorySearch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMemoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__memory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMemory"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMemoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    insert_profile_api_v1_profiles_insert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileInsertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    flush_profile_api_v1_profiles_flush_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileFlushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileFlushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile_api_v1_profiles__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_context_api_v1_profiles__user_id__context_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileContextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_profile_item_api_v1_profiles__user_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileAddItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileAddItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_profile_item_api_v1_profiles__user_id__items__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDeleteItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_datasets_api_v1_knowledge_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDatasetListResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_dataset_api_v1_knowledge_datasets_post: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDatasetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_dataset_api_v1_knowledge_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDeleteResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_knowledge_api_v1_knowledge_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeAddResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cognify_api_v1_knowledge_cognify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeCognifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeCognifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_knowledge_api_v1_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_cognify_status_api_v1_knowledge_cognify_status__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CognifyStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dataset_graph_api_v1_knowledge_datasets__dataset_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetGraphResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_knowledge_api_v1_knowledge_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_unified_context_api_v1_context_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    get_uuid_api_v1_users__user_id__uuid_get: {
        parameters: {
            query?: {
                /** @description 为 true 时：若映射不存在则自动创建（幂等）；为 false 时（默认）：映射不存在返回 404，不写入 Redis。 */
                create?: boolean;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回已有映射或（create=true 时）新建的 UUID v4 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMappingResponse"];
                };
            };
            /** @description 映射不存在（create=false 时） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_uuid_mapping_api_v1_users__user_id__uuid_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMappingDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_user_api_v1_backup_export__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_bundle_api_v1_backup_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackupImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_v1_admin_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyListResponse"];
                };
            };
        };
    };
    create_key_api_v1_admin_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_api_v1_admin_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_key_api_v1_admin_api_keys__key_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_key_api_v1_admin_api_keys__key_id__rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_key_logs_api_v1_admin_api_keys__key_id__logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
